version: '3'
services:
  daneshkar:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1